services:
  nginx:
    container_name: nginx
    build: 
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
  edb-api:
    container_name: rust-edb-api
    build: 
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./data:/data
